complexity:
  LongParameterList:
    ignoreDefaultParameters: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  ForbiddenComment:
    comments:
      - reason: "TODO without assignee â€” add a name or issue link"
        value: "TODO(?!\\()"

potential-bugs:
  DoubleMutabilityForCollection:
    active: true
  UnsafeCallOnNullableType:
    active: true

performance:
  ArrayPrimitive:
    active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true

formatting:
  MaximumLineLength:
    active: false
